import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = resolve(projectRoot, ".env");
const outputPath = resolve(projectRoot, "assets/js/config.js");

const values = {};
const envFile = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";

for (const rawLine of envFile.split(/\r?\n/)) {
  const line = rawLine.trim();
  if (!line || line.startsWith("#")) continue;

  const separator = line.indexOf("=");
  if (separator === -1) continue;

  const key = line.slice(0, separator).trim();
  let value = line.slice(separator + 1).trim();
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    value = value.slice(1, -1);
  }
  values[key] = value;
}

function toWhatsAppNumber(value) {
  const number = (value || "").replace(/\D/g, "");
  // Local Syrian mobile numbers (09xxxxxxxx) need the country code for wa.me.
  return number.startsWith("0") ? `963${number.slice(1)}` : number;
}

// Server variables take precedence; .env keeps local previews working.
const menWhatsappLinkNumber = toWhatsAppNumber(
  process.env.MEN_WHATSAPP_NUMBER ||
  process.env.WHATSAPP_NUMBER ||
  values.MEN_WHATSAPP_NUMBER ||
  values.WHATSAPP_NUMBER
);
const womenWhatsappLinkNumber = toWhatsAppNumber(
  process.env.WOMEN_WHATSAPP_NUMBER ||
  values.WOMEN_WHATSAPP_NUMBER
);
// Display values never use the international link number, so visitors see the
// exact local format chosen in the server settings (or .env during preview).
const menWhatsappDisplayNumber =
  process.env.DISPLAY_M_NUMBER ||
  values.DISPLAY_M_NUMBER ||
  values.WHATSAPP_NUMBER ||
  "";
const womenWhatsappDisplayNumber =
  process.env.DISPLAY_W_NUMBER ||
  values.DISPLAY_W_NUMBER ||
  values.WOMEN_WHATSAPP_NUMBER ||
  "";
const contactEmail =
  process.env.CONTACT_EMAIL || values.CONTACT_EMAIL || "";

const generatedConfig = `// Generated from .env — do not edit this file directly.
window.SITE_CONFIG = ${JSON.stringify(
  {
    // WHATSAPP_NUMBER is retained for backwards compatibility.
    WHATSAPP_NUMBER: menWhatsappLinkNumber,
    MEN_WHATSAPP_NUMBER: menWhatsappLinkNumber,
    WOMEN_WHATSAPP_NUMBER: womenWhatsappLinkNumber,
    MEN_WHATSAPP_DISPLAY_NUMBER: menWhatsappDisplayNumber,
    WOMEN_WHATSAPP_DISPLAY_NUMBER: womenWhatsappDisplayNumber,
    CONTACT_EMAIL: contactEmail,
    WHATSAPP_DEFAULT_MESSAGE:
      "مرحباً نادي المنصور، أود الاشتراك معكم.",
    MEN_WHATSAPP_DEFAULT_MESSAGE:
      "مرحباً نادي المنصور، أود الاستفسار عن تدريب الرجال والاشتراكات.",
    WOMEN_WHATSAPP_DEFAULT_MESSAGE:
      "مرحباً نادي المنصور، أود الاستفسار عن حصص السيدات والاشتراكات.",
  },
  null,
  2
)};
`;

writeFileSync(outputPath, generatedConfig, "utf8");
console.log("Generated assets/js/config.js from environment variables");
