import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const envPath = resolve(projectRoot, ".env");
const outputPath = resolve(projectRoot, "assets/js/config.js");

const values = {};
const envFile = existsSync(envPath) ? readFileSync(envPath, "utf8") : "";

for (const rawLine of envFile.split(/\r?\n/)) {
  const line = rawLine.trim();
  if (!line || line.startsWith("#")) continue;

  const separator = line.indexOf("=");
  if (separator === -1) continue;

  const key = line.slice(0, separator).trim();
  let value = line.slice(separator + 1).trim();
  if (
    (value.startsWith('"') && value.endsWith('"')) ||
    (value.startsWith("'") && value.endsWith("'"))
  ) {
    value = value.slice(1, -1);
  }
  values[key] = value;
}

// WhatsApp links use server variables only, so their target is managed from
// deployment settings rather than the repository's local .env file.
const menWhatsappLinkNumber = (
  process.env.MEN_WHATSAPP_NUMBER ||
  process.env.WHATSAPP_NUMBER ||
  ""
).replace(/\D/g, "");
const womenWhatsappLinkNumber = (
  process.env.WOMEN_WHATSAPP_NUMBER ||
  ""
).replace(/\D/g, "");
// The phone number printed on the page is sourced from .env only.
const menWhatsappDisplayNumber = (values.WHATSAPP_NUMBER || "").replace(/\D/g, "");
const womenWhatsappDisplayNumber = (values.WOMEN_WHATSAPP_NUMBER || "").replace(
  /\D/g,
  ""
);
const contactEmail =
  process.env.CONTACT_EMAIL || values.CONTACT_EMAIL || "";

const generatedConfig = `// Generated from .env — do not edit this file directly.
window.SITE_CONFIG = ${JSON.stringify(
  {
    // WHATSAPP_NUMBER is retained for backwards compatibility.
    WHATSAPP_NUMBER: menWhatsappLinkNumber,
    MEN_WHATSAPP_NUMBER: menWhatsappLinkNumber,
    WOMEN_WHATSAPP_NUMBER: womenWhatsappLinkNumber,
    MEN_WHATSAPP_DISPLAY_NUMBER: menWhatsappDisplayNumber,
    WOMEN_WHATSAPP_DISPLAY_NUMBER: womenWhatsappDisplayNumber,
    CONTACT_EMAIL: contactEmail,
    WHATSAPP_DEFAULT_MESSAGE:
      "مرحباً نادي المنصور، أود الاشتراك معكم.",
    MEN_WHATSAPP_DEFAULT_MESSAGE:
      "مرحباً نادي المنصور، أود الاستفسار عن تدريب الرجال والاشتراكات.",
    WOMEN_WHATSAPP_DEFAULT_MESSAGE:
      "مرحباً نادي المنصور، أود الاستفسار عن حصص السيدات والاشتراكات.",
  },
  null,
  2
)};
`;

writeFileSync(outputPath, generatedConfig, "utf8");
console.log("Generated assets/js/config.js from environment variables");
